# database with engine information about all objects (shared between importer and exporter)

object_info = {   
		0: {   'filename': 'gfx/spielerstart.bmp',
			   'name': 'Player start',
			   'type': 'player_start',
			   'xfc': 1,
			   'xfs': 70,
			   'xs': 70,
			   'yfc': 1,
			   'yfs': 80,
			   'ys': 80},
		1: {   'filename': 'oneup.png',
			   'name': 'One-Up',
			   'type': 'one_up',
			   'xfc': 5,
			   'xfs': 40,
			   'xs': 200,
			   'yfc': 4,
			   'yfs': 40,
			   'ys': 160},
		2: {   'filename': 'diamant.bmp',
			   'name': 'Diamond',
			   'type': 'diamond',
			   'xfc': 9,
			   'xfs': 29,
			   'xs': 261,
			   'yfc': 1,
			   'yfs': 29,
			   'ys': 29},
		3: {   'filename': 'powerblock.png',
			   'name': 'PowerBlock',
			   'type': 'powerblock',
			   'xfc': 11,
			   'xfs': 40,
			   'xs': 440,
			   'yfc': 1,
			   'yfs': 40,
			   'ys': 40},
		4: {   'filename': 'spitter.bmp',
			   'name': 'Spitter',
			   'type': 'spitter',
			   'xfc': 5,
			   'xfs': 22,
			   'xs': 110,
			   'yfc': 1,
			   'yfs': 23,
			   'ys': 23},
		5: {   'filename': 'enemy-walker.bmp',
			   'name': 'Walker',
			   'type': 'walker',
			   'xfc': 8,
			   'xfs': 45,
			   'xs': 360,
			   'yfc': 4,
			   'yfs': 45,
			   'ys': 180},
		6: {   'filename': 'enemy-guntower.bmp',
			   'name': 'GunTower',
			   'type': 'guntower',
			   'xfc': 5,
			   'xfs': 60,
			   'xs': 300,
			   'yfc': 3,
			   'yfs': 40,
			   'ys': 120},
		7: {   'filename': 'spiderbomb.bmp',
			   'name': 'Spinnenbombe',
			   'type': 'spinnenbombe',
			   'xfc': 7,
			   'xfs': 50,
			   'xs': 350,
			   'yfc': 1,
			   'yfs': 34,
			   'ys': 34},
		8: {   'filename': 'piranha.bmp',
			   'name': 'Piranha',
			   'type': 'piranha',
			   'xfc': 5,
			   'xfs': 45,
			   'xs': 225,
			   'yfc': 8,
			   'yfs': 29,
			   'ys': 232},
		9: {   'filename': 'stahlmuecke.bmp',
			   'name': 'Stahlmuecke',
			   'type': 'stahlmuecke',
			   'xfc': 5,
			   'xfs': 34,
			   'xs': 170,
			   'yfc': 2,
			   'yfs': 35,
			   'ys': 70},
		10: {   'filename': 'deckenturm.bmp',
				'name': 'Deckenturm',
				'type': 'deckenturm',
				'xfc': 5,
				'xfs': 38,
				'xs': 190,
				'yfc': 6,
				'yfs': 40,
				'ys': 240},
		11: {   'filename': 'kugel4.bmp',
				'name': 'Kugel klein',
				'type': 'kugel_klein',
				'xfc': 5,
				'xfs': 30,
				'xs': 150,
				'yfc': 4,
				'yfs': 30,
				'ys': 120},
		12: {   'filename': 'kugel3.bmp',
				'name': 'Kugel medium',
				'type': 'kugel_medium',
				'xfc': 5,
				'xfs': 45,
				'xs': 225,
				'yfc': 4,
				'yfs': 45,
				'ys': 180},
		13: {   'filename': 'kugel2.bmp',
				'name': 'Kugel gross',
				'type': 'kugel_gross',
				'xfc': 5,
				'xfs': 60,
				'xs': 300,
				'yfc': 4,
				'yfs': 60,
				'ys': 240},
		14: {   'filename': 'kugel1.bmp',
				'name': 'Kugel riesig',
				'type': 'kugel_riesig',
				'xfc': 5,
				'xfs': 90,
				'xs': 450,
				'yfc': 4,
				'yfs': 90,
				'ys': 360},
		15: {   'filename': 'krabbleroben.bmp',
				'name': 'Krabbler oben',
				'type': 'krabbler_oben',
				'xfc': 5,
				'xfs': 50,
				'xs': 250,
				'yfc': 3,
				'yfs': 75,
				'ys': 225},
		16: {   'filename': 'krabblerlinks.bmp',
				'name': 'Krabbler Links',
				'type': 'krabbler_links',
				'xfc': 3,
				'xfs': 75,
				'xs': 225,
				'yfc': 5,
				'yfs': 50,
				'ys': 250},
		17: {   'filename': 'krabblerrechts.bmp',
				'name': 'Krabbler Rechts',
				'type': 'krabbler_rechts',
				'xfc': 3,
				'xfs': 75,
				'xs': 225,
				'yfc': 5,
				'yfs': 50,
				'ys': 250},
		18: {   'filename': 'auge.bmp',
				'name': 'Auge Extracontainer',
				'type': 'auge_extracontainer',
				'xfc': 6,
				'xfs': 60,
				'xs': 360,
				'yfc': 1,
				'yfs': 26,
				'ys': 26},
		19: {   'filename': 'qualle.bmp',
				'name': 'Qualle',
				'type': 'qualle',
				'xfc': 6,
				'xfs': 40,
				'xs': 240,
				'yfc': 3,
				'yfs': 60,
				'ys': 180},
		20: {   'filename': 'fallingstone.bmp',
				'name': 'Fallender Stein',
				'type': 'fallender_stein',
				'xfc': 1,
				'xfs': 80,
				'xs': 80,
				'yfc': 1,
				'yfs': 40,
				'ys': 40},
		21: {   'filename': 'fallingstone2.bmp',
				'name': 'Broeselnder Stein',
				'type': 'broeselnder_stein',
				'xfc': 2,
				'xfs': 80,
				'xs': 160,
				'yfc': 1,
				'yfs': 40,
				'ys': 40},
		22: {   'filename': 'roboraupe.bmp',
				'name': 'Robo Raupe',
				'type': 'robo_raupe',
				'xfc': 4,
				'xfs': 90,
				'xs': 360,
				'yfc': 3,
				'yfs': 35,
				'ys': 105},
		23: {   'filename': 'stalagtit.bmp',
				'name': 'Stalagtit',
				'type': 'stalagtit',
				'xfc': 1,
				'xfs': 40,
				'xs': 40,
				'yfc': 1,
				'yfs': 80,
				'ys': 80},
		24: {   'filename': 'raketenwerfer.bmp',
				'name': 'Raketenwerfer',
				'type': 'raketenwerfer',
				'xfc': 5,
				'xfs': 45,
				'xs': 225,
				'yfc': 2,
				'yfs': 25,
				'ys': 50},
		25: {   'filename': 'swimwalker.bmp',
				'name': 'SwimWalker',
				'type': 'swimwalker',
				'xfc': 4,
				'xfs': 65,
				'xs': 260,
				'yfc': 3,
				'yfs': 45,
				'ys': 135},
		26: {   'filename': 'flugsack.bmp',
				'name': 'FlugSack',
				'type': 'flugsack',
				'xfc': 4,
				'xfs': 80,
				'xs': 320,
				'yfc': 3,
				'yfs': 70,
				'ys': 210},
		27: {   'filename': 'flugsack.bmp',
				'name': 'FlugSack zum drauf reiten =)',
				'type': 'flugsack_zum_drauf_reiten_',
				'xfc': 4,
				'xfs': 80,
				'xs': 320,
				'yfc': 3,
				'yfs': 70,
				'ys': 210},
		28: {   'filename': 'eisstachel.bmp',
				'name': 'EisStachel',
				'type': 'eisstachel',
				'xfc': 4,
				'xfs': 105,
				'xs': 420,
				'yfc': 5,
				'yfs': 78,
				'ys': 390},
		29: {   'filename': 'skiwalker.bmp',
				'name': 'Ski-Walker',
				'type': 'ski_walker',
				'xfc': 3,
				'xfs': 65,
				'xs': 195,
				'yfc': 4,
				'yfs': 38,
				'ys': 152},
		30: {   'filename': 'flugkanone.bmp',
				'name': 'Flugkanone',
				'type': 'flugkanone',
				'xfc': 4,
				'xfs': 65,
				'xs': 260,
				'yfc': 5,
				'yfs': 45,
				'ys': 225},
		31: {   'filename': 'snowbomb.bmp',
				'name': 'Schnee Bombe',
				'type': 'schnee_bombe',
				'xfc': 6,
				'xfs': 80,
				'xs': 480,
				'yfc': 4,
				'yfs': 80,
				'ys': 320},
		32: {   'filename': 'roboman1.bmp',
				'name': 'Robo Flug Raketen',
				'type': 'robo_flug_raketen',
				'xfc': 5,
				'xfs': 90,
				'xs': 450,
				'yfc': 3,
				'yfs': 100,
				'ys': 300},
		33: {   'filename': 'boulder.bmp',
				'name': 'Blauer Boulder',
				'type': 'blauer_boulder',
				'xfc': 5,
				'xfs': 60,
				'xs': 300,
				'yfc': 3,
				'yfs': 55,
				'ys': 165},
		34: {   'filename': 'stelzsack.bmp',
				'name': 'Stelzsack',
				'type': 'stelzsack',
				'xfc': 5,
				'xfs': 100,
				'xs': 500,
				'yfc': 4,
				'yfs': 147,
				'ys': 441},
		35: {   'filename': 'fallbombe.bmp',
				'name': 'Fall Bombe',
				'type': 'fall_bombe',
				'xfc': 6,
				'xfs': 23,
				'xs': 138,
				'yfc': 1,
				'yfs': 59,
				'ys': 59},
		36: {   'filename': 'pokenuke.bmp',
				'name': 'Poke Nuke',
				'type': 'poke_nuke',
				'xfc': 1,
				'xfs': 81,
				'xs': 81,
				'yfc': 1,
				'yfs': 217,
				'ys': 217},
		37: {   'filename': 'lavakrabbe.bmp',
				'name': 'Lava Krabbe',
				'type': 'lava_krabbe',
				'xfc': 4,
				'xfs': 70,
				'xs': 280,
				'yfc': 4,
				'yfs': 34,
				'ys': 136},
		38: {   'filename': 'lavaball.bmp',
				'name': 'Lava Ball Spawner',
				'type': 'lava_ball_spawner',
				'xfc': 5,
				'xfs': 60,
				'xs': 300,
				'yfc': 4,
				'yfs': 60,
				'ys': 240},
		39: {   'filename': 'lavaball.bmp',
				'name': 'Lava Ball',
				'type': 'lava_ball',
				'xfc': 5,
				'xfs': 60,
				'xs': 300,
				'yfc': 4,
				'yfs': 60,
				'ys': 240},
		40: {   'filename': 'fettespinne.png',
				'name': 'Fette Spinne',
				'type': 'fette_spinne',
				'xfc': 4,
				'xfs': 104,
				'xs': 416,
				'yfc': 5,
				'yfs': 69,
				'ys': 414},
		41: {   'filename': 'eiermann.bmp',
				'name': 'Eiermann',
				'type': 'eiermann',
				'xfc': 5,
				'xfs': 62,
				'xs': 310,
				'yfc': 2,
				'yfs': 66,
				'ys': 132},
		42: {   'filename': 'wandcannon.bmp',
				'name': 'Wandcannon',
				'type': 'wandcannon',
				'xfc': 3,
				'xfs': 47,
				'xs': 141,
				'yfc': 1,
				'yfs': 32,
				'ys': 32},
		43: {   'filename': 'starsmall.bmp',
				'name': 'Star Small',
				'type': 'star_small',
				'xfc': 2,
				'xfs': 40,
				'xs': 80,
				'yfc': 2,
				'yfs': 40,
				'ys': 80},
		44: {   'filename': 'starbig.bmp',
				'name': 'Star Big',
				'type': 'star_big',
				'xfc': 2,
				'xfs': 80,
				'xs': 160,
				'yfc': 2,
				'yfs': 80,
				'ys': 160},
		45: {   'filename': 'made.bmp',
				'name': 'Made',
				'type': 'made',
				'xfc': 10,
				'xfs': 20,
				'xs': 200,
				'yfc': 2,
				'yfs': 20,
				'ys': 40},
		46: {   'filename': 'drone.bmp',
				'name': 'Drone',
				'type': 'drone',
				'xfc': 4,
				'xfs': 70,
				'xs': 280,
				'yfc': 3,
				'yfs': 80,
				'ys': 240},
		47: {   'filename': 'neufisch.bmp',
				'name': 'Neuer Fisch',
				'type': 'neuer_fisch',
				'xfc': 4,
				'xfs': 90,
				'xs': 360,
				'yfc': 4,
				'yfs': 73,
				'ys': 292},
		48: {   'filename': 'pflanze.bmp',
				'name': 'Super Mario Pflanze',
				'type': 'super_mario_pflanze',
				'xfc': 4,
				'xfs': 110,
				'xs': 440,
				'yfc': 5,
				'yfs': 90,
				'ys': 450},
		49: {   'filename': 'spitterbombe.bmp',
				'name': 'Spitterbombe',
				'type': 'spitterbombe',
				'xfc': 6,
				'xfs': 29,
				'xs': 174,
				'yfc': 1,
				'yfs': 50,
				'ys': 50},
		50: {   'filename': 'nest.bmp',
				'name': 'Wespennest',
				'type': 'wespennest',
				'xfc': 1,
				'xfs': 43,
				'xs': 43,
				'yfc': 1,
				'yfs': 60,
				'ys': 60},
		51: {   'filename': 'schienenviech.bmp',
				'name': 'Schienenviech',
				'type': 'schienenviech',
				'xfc': 1,
				'xfs': 49,
				'xs': 245,
				'yfc': 1,
				'yfs': 40,
				'ys': 40},
		52: {   'filename': 'wassermine.bmp',
				'name': 'Wassermine',
				'type': 'wassermine',
				'xfc': 5,
				'xfs': 60,
				'xs': 300,
				'yfc': 2,
				'yfs': 90,
				'ys': 190},
		53: {   'filename': 'fledermaus.bmp',
				'name': 'Fledermaus',
				'type': 'fledermaus',
				'xfc': 10,
				'xfs': 50,
				'xs': 500,
				'yfc': 3,
				'yfs': 58,
				'ys': 174},
		54: {   'filename': 'climbspider.bmp',
				'name': 'Climb Spider',
				'type': 'climb_spider',
				'xfc': 5,
				'xfs': 50,
				'xs': 250,
				'yfc': 3,
				'yfs': 35,
				'ys': 105},
		55: {   'filename': 'feuerspinne.bmp',
				'name': 'Fire Spider',
				'type': 'fire_spider',
				'xfc': 6,
				'xfs': 80,
				'xs': 480,
				'yfc': 2,
				'yfs': 55,
				'ys': 110},
		56: {   'filename': 'ballerdrone.bmp',
				'name': 'Ballerdrone',
				'type': 'ballerdrone',
				'xfc': 5,
				'xfs': 90,
				'xs': 450,
				'yfc': 3,
				'yfs': 65,
				'ys': 195},
		57: {   'filename': 'schwabbel.bmp',
				'name': 'Schwabbelviech',
				'type': 'schwabbelviech',
				'xfc': 5,
				'xfs': 60,
				'xs': 300,
				'yfc': 4,
				'yfs': 60,
				'ys': 240},
		58: {   'filename': 'bigrocket.bmp',
				'name': 'Big Rocket',
				'type': 'big_rocket',
				'xfc': 8,
				'xfs': 73,
				'xs': 578,
				'yfc': 2,
				'yfs': 300,
				'ys': 600},
		59: {   'filename': 'eiszapfen.png',
				'name': 'Eiszapfen',
				'type': 'eiszapfen',
				'xfc': 1,
				'xfs': 30,
				'xs': 30,
				'yfc': 1,
				'yfs': 100,
				'ys': 100},
		60: {   'filename': 'wandkrabbe.bmp',
				'name': 'Wandkrabbe',
				'type': 'wandkrabbe',
				'xfc': 4,
				'xfs': 34,
				'xs': 136,
				'yfc': 3,
				'yfs': 64,
				'ys': 192},
		61: {   'filename': 'jaeger.bmp',
				'name': 'Abfangjaeger',
				'type': 'abfangjaeger',
				'xfc': 4,
				'xfs': 70,
				'xs': 280,
				'yfc': 4,
				'yfs': 53,
				'ys': 212},
		62: {   'filename': 'siderocket.bmp',
				'name': 'Wandrakete',
				'type': 'wandrakete',
				'xfc': 1,
				'xfs': 40,
				'xs': 40,
				'yfc': 1,
				'yfs': 18,
				'ys': 18},
		63: {   'filename': 'fiesedrone.bmp',
				'name': 'Fiese kleine Drone',
				'type': 'fiese_kleine_drone',
				'xfc': 4,
				'xfs': 50,
				'xs': 200,
				'yfc': 3,
				'yfs': 50,
				'ys': 150},
		64: {   'filename': 'gfx/nix.bmp',
				'name': 'Schleimboller',
				'type': 'schleimboller',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		65: {   'filename': 'gfx/nix.bmp',
				'name': 'Schleim Alien',
				'type': 'schleim_alien',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		66: {   'filename': 'gfx/nix.bmp',
				'name': 'Schleim Maul',
				'type': 'schleim_maul',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		67: {   'filename': 'gfx/nix.bmp',
				'name': 'Fieser Walker',
				'type': 'fieser_walker',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		68: {   'filename': 'gfx/nix.bmp',
				'name': 'Fieser Fire Walker',
				'type': 'fieser_fire_walker',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		69: {   'filename': 'gfx/nix.bmp',
				'name': 'Mittelgrosse Spinne',
				'type': 'mittelgrosse_spinne',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		70: {   'filename': 'gfx/nix.bmp',
				'name': 'Small Wespe',
				'type': 'small_wespe',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		71: {   'filename': 'gfx/nix.bmp',
				'name': 'Deckenkrabbe',
				'type': 'deckenkrabbe',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		72: {   'filename': 'gfx/nix.bmp',
				'name': 'Stampfstein',
				'type': 'stampfstein',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		73: {   'filename': 'gfx/nix.bmp',
				'name': 'Lavamann',
				'type': 'lavamann',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		74: {   'filename': 'gfx/nix.bmp',
				'name': 'La Fass J',
				'type': 'la_fass_j',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		75: {   'filename': 'gfx/nix.bmp',
				'name': 'Geschuetzturm',
				'type': 'geschuetzturm',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		76: {   'filename': 'gfx/nix.bmp',
				'name': 'Fette Rakete',
				'type': 'fette_rakete',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		77: {   'filename': 'gfx/nix.bmp',
				'name': 'Schabe',
				'type': 'schabe',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		78: {   'filename': 'gfx/nix.bmp',
				'name': 'Mini Dragon',
				'type': 'mini_dragon',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		79: {   'filename': 'gfx/nix.bmp',
				'name': 'schneekoppe',
				'type': 'schneekoppe',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		80: {   'filename': 'gfx/nix.bmp',
				'name': 'Zitrone',
				'type': 'zitrone',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		81: {   'filename': 'gfx/nix.bmp',
				'name': 'Rotzpott',
				'type': 'rotzpott',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		82: {   'filename': 'gfx/nix.bmp',
				'name': 'Stachelbeere',
				'type': 'stachelbeere',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		83: {   'filename': 'gfx/nix.bmp',
				'name': 'Minirocket',
				'type': 'minirocket',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		84: {   'filename': 'gfx/nix.bmp',
				'name': 'Mutant',
				'type': 'mutant',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		85: {   'filename': 'gfx/nix.bmp',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		86: {   'filename': 'gfx/nix.bmp',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		87: {   'filename': 'gfx/nix.bmp',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		88: {   'filename': 'gfx/nix.bmp',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		89: {   'filename': 'gfx/nix.bmp',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		90: {   'filename': 'gfx/nix.bmp',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		91: {   'filename': 'gfx/nix.bmp',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		92: {   'filename': 'gfx/nix.bmp',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		93: {   'filename': 'gfx/nix.bmp',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		94: {   'filename': 'gfx/nix.bmp',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		95: {   'filename': 'gfx/nix.bmp',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		96: {   'filename': 'gfx/nix.bmp',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		97: {   'filename': 'gfx/nix.bmp',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		98: {   'filename': 'gfx/nix.bmp',
				'xfc': 6,
				'xfs': 32,
				'xs': 32,
				'yfc': 3,
				'yfs': 32,
				'ys': 32},
		99: {'name': 'Punisher', 'type': 'punisher'},
		100: {   'filename': 'riesenpiranha.bmp',
				 'name': 'Riesen Piranha',
				 'type': 'riesen_piranha',
				 'xfc': 4,
				 'xfs': 256,
				 'xs': 1024,
				 'yfc': 2,
				 'yfs': 210,
				 'ys': 420},
		101: {   'filename': 'riesenqualle.bmp',
				 'name': 'Riesen Qualle',
				 'type': 'riesen_qualle',
				 'xfc': 3,
				 'xfs': 130,
				 'xs': 390,
				 'yfc': 2,
				 'yfs': 240,
				 'ys': 480},
		102: {   'filename': 'riesenraupe.bmp',
				 'name': 'Riesen Raupe',
				 'type': 'riesen_raupe',
				 'xfc': 3,
				 'xfs': 180,
				 'xs': 540,
				 'yfc': 5,
				 'yfs': 58,
				 'ys': 290},
		103: {   'filename': 'wasp.png',
				 'name': 'Riesen Wespe',
				 'type': 'riesen_wespe',
				 'xfc': 2,
				 'xfs': 116,
				 'xs': 232,
				 'yfc': 3,
				 'yfs': 100,
				 'ys': 300},
		104: {   'filename': 'gfx/nix.bmp',
				 'xfc': 1,
				 'xfs': 32,
				 'xs': 32,
				 'yfc': 1,
				 'yfs': 32,
				 'ys': 32},
		105: {   'filename': 'gfx/nix.bmp',
				 'xfc': 1,
				 'xfs': 32,
				 'xs': 32,
				 'yfc': 1,
				 'yfs': 32,
				 'ys': 32},
		106: {   'filename': 'gfx/nix.bmp',
				 'xfc': 1,
				 'xfs': 32,
				 'xs': 32,
				 'yfc': 1,
				 'yfs': 32,
				 'ys': 32},
		107: {   'filename': 'gfx/nix.bmp',
				 'xfc': 1,
				 'xfs': 32,
				 'xs': 32,
				 'yfc': 1,
				 'yfs': 32,
				 'ys': 32},
		108: {   'filename': 'gfx/nix.bmp',
				 'xfc': 1,
				 'xfs': 32,
				 'xs': 32,
				 'yfc': 1,
				 'yfs': 32,
				 'ys': 32},
		109: {   'filename': 'gfx/nix.bmp',
				 'xfc': 1,
				 'xfs': 32,
				 'xs': 32,
				 'yfc': 1,
				 'yfs': 32,
				 'ys': 32},
		110: {   'filename': 'gfx/nix.bmp',
				 'xfc': 1,
				 'xfs': 32,
				 'xs': 32,
				 'yfc': 1,
				 'yfs': 32,
				 'ys': 32},
		111: {   'filename': 'gfx/nix.bmp',
				 'xfc': 1,
				 'xfs': 32,
				 'xs': 32,
				 'yfc': 1,
				 'yfs': 32,
				 'ys': 32},
		112: {   'filename': 'gfx/nix.bmp',
				 'xfc': 1,
				 'xfs': 32,
				 'xs': 32,
				 'yfc': 1,
				 'yfs': 32,
				 'ys': 32},
		113: {   'filename': 'gfx/nix.bmp',
				 'xfc': 1,
				 'xfs': 32,
				 'xs': 32,
				 'yfc': 1,
				 'yfs': 32,
				 'ys': 32},
		114: {   'filename': 'gfx/nix.bmp',
				 'xfc': 1,
				 'xfs': 32,
				 'xs': 32,
				 'yfc': 1,
				 'yfs': 32,
				 'ys': 32},
		115: {   'filename': 'gfx/nix.bmp',
				 'xfc': 1,
				 'xfs': 32,
				 'xs': 32,
				 'yfc': 1,
				 'yfs': 32,
				 'ys': 32},
		116: {   'filename': 'gfx/nix.bmp',
				 'xfc': 1,
				 'xfs': 32,
				 'xs': 32,
				 'yfc': 1,
				 'yfs': 32,
				 'ys': 32},
		117: {   'filename': 'gfx/nix.bmp',
				 'xfc': 1,
				 'xfs': 32,
				 'xs': 32,
				 'yfc': 1,
				 'yfs': 32,
				 'ys': 32},
		118: {   'filename': 'gfx/nix.bmp',
				 'xfc': 1,
				 'xfs': 32,
				 'xs': 32,
				 'yfc': 1,
				 'yfs': 32,
				 'ys': 32},
		120: {   'filename': 'stahlfaust.bmp',
				 'name': 'Stahlfaust Boss',
				 'type': 'stahlfaust_boss',
				 'xfc': 2,
				 'xfs': 256,
				 'xs': 512,
				 'yfc': 1,
				 'yfs': 264,
				 'ys': 264},
		121: {   'filename': 'pharaokopf.bmp',
				 'name': 'Pharao Kopf Boss',
				 'type': 'pharao_kopf_boss',
				 'xfc': 2,
				 'xfs': 224,
				 'xs': 448,
				 'yfc': 2,
				 'yfs': 224,
				 'ys': 448},
		122: {   'filename': 'spiderboss_rumpf.png',
				 'name': 'Riesenspinnen Boss',
				 'type': 'riesenspinnen_boss',
				 'xfc': 1,
				 'xfs': 415,
				 'xs': 415,
				 'yfc': 1,
				 'yfs': 160,
				 'ys': 160},
		123: {   'filename': 'ufo.bmp',
				 'name': 'Boeser Hurrican',
				 'type': 'boeser_hurrican',
				 'xfc': 3,
				 'xfs': 200,
				 'xs': 600,
				 'yfc': 7,
				 'yfs': 94,
				 'ys': 658},
		124: {   'filename': 'ufo.bmp',
				 'name': 'Ufo',
				 'type': 'ufo',
				 'xfc': 3,
				 'xfs': 200,
				 'xs': 600,
				 'yfc': 7,
				 'yfs': 94,
				 'ys': 658},
		125: {   'filename': 'fahrstuhlboss_rahmen.bmp',
				 'name': 'Fahrstuhl Boss',
				 'type': 'fahrstuhl_boss',
				 'xfc': 1,
				 'xfs': 420,
				 'xs': 420,
				 'yfc': 1,
				 'yfs': 280,
				 'ys': 280},
		126: {   'filename': 'flugboss_main.png',
				 'name': 'Flugboss',
				 'type': 'flugboss',
				 'xfc': 1,
				 'xfs': 280,
				 'xs': 280,
				 'yfc': 1,
				 'yfs': 285,
				 'ys': 285},
		127: {   'filename': 'bratklops0000.bmp',
				 'name': 'Bratklops',
				 'type': 'bratklops',
				 'xfc': 1,
				 'xfs': 232,
				 'xs': 232,
				 'yfc': 1,
				 'yfs': 400,
				 'ys': 400},
		128: {   'filename': 'gfx/trschmidt.bmp',
				 'name': 'T.R.Schmidt Orgie J',
				 'type': 't_r_schmidt_orgie_j',
				 'xfc': 1,
				 'xfs': 40,
				 'xs': 40,
				 'yfc': 1,
				 'yfs': 40,
				 'ys': 40},
		129: {   'filename': 'metalhead_birne.bmp',
				 'name': 'Stahlkopp',
				 'type': 'stahlkopp',
				 'xfc': 1,
				 'xfs': 204,
				 'xs': 204,
				 'yfc': 1,
				 'yfs': 242,
				 'ys': 242},
		130: {   'filename': 'stahlfaust_eis.bmp',
				 'name': 'Eisfaust',
				 'type': 'eisfaust',
				 'xfc': 2,
				 'xfs': 256,
				 'xs': 512,
				 'yfc': 1,
				 'yfs': 264,
				 'ys': 264},
		131: {   'filename': 'gfx/wuxe.bmp',
				 'name': 'Wuxe Spinnen',
				 'type': 'wuxe_spinnen',
				 'xfc': 1,
				 'xfs': 40,
				 'xs': 40,
				 'yfc': 1,
				 'yfs': 40,
				 'ys': 40},
		132: {   'filename': 'golem_rumpf.png',
				 'name': 'Golem',
				 'type': 'golem',
				 'xfc': 1,
				 'xfs': 185,
				 'xs': 185,
				 'yfc': 1,
				 'yfs': 291,
				 'ys': 291},
		133: {   'filename': 'spinnenmaschine_oben.png',
				 'name': 'Spinnenmaschine',
				 'type': 'spinnenmaschine',
				 'xfc': 1,
				 'xfs': 317,
				 'xs': 317,
				 'yfc': 1,
				 'yfs': 413,
				 'ys': 413},
		134: {   'filename': 'drache_body.png',
				 'name': 'Metall Drache',
				 'type': 'metall_drache',
				 'xfc': 1,
				 'xfs': 201,
				 'xs': 201,
				 'yfc': 1,
				 'yfs': 147,
				 'ys': 147},
		135: {   'filename': 'rollmops_rollen.png',
				 'name': 'Rollmops',
				 'type': 'rollmops',
				 'xfc': 5,
				 'xfs': 130,
				 'xs': 650,
				 'yfc': 2,
				 'yfs': 130,
				 'ys': 260},
		136: {   'filename': 'schneekoenig.png',
				 'name': 'Schneekoenig',
				 'type': 'schneekoenig',
				 'xfc': 4,
				 'xfs': 200,
				 'xs': 800,
				 'yfc': 3,
				 'yfs': 200,
				 'ys': 600},
		137: {   'filename': 'bigfish.bmp',
				 'name': 'Bigfisch',
				 'type': 'bigfisch',
				 'xfc': 1,
				 'xfs': 208,
				 'xs': 208,
				 'yfc': 1,
				 'yfs': 157,
				 'ys': 157},
		138: {   'filename': 'skeletor.png',
				 'name': 'Skeletor',
				 'type': 'skeletor',
				 'xfc': 8,
				 'xfs': 125,
				 'xs': 1000,
				 'yfc': 2,
				 'yfs': 200,
				 'ys': 400},
		139: {   'filename': 'endbossmaschine.png',
				 'name': 'The Wall',
				 'type': 'the_wall',
				 'xfc': 1,
				 'xfs': 285,
				 'xs': 285,
				 'yfc': 1,
				 'yfs': 480,
				 'ys': 480},
		140: {   'filename': 'gfx/partikelspawner.bmp',
				 'name': 'Partikel-Generator',
				 'type': 'partikel_generator',
				 'xfc': 1,
				 'xfs': 40,
				 'xs': 40,
				 'yfc': 1,
				 'yfs': 40,
				 'ys': 40},
		141: {   'filename': 'fahrstuhl.bmp',
				 'name': 'Elevator',
				 'type': 'elevator',
				 'xfc': 1,
				 'xfs': 400,
				 'xs': 400,
				 'yfc': 1,
				 'yfs': 154,
				 'ys': 154},
		142: {   'filename': 'fass.png',
				 'name': 'Fass',
				 'type': 'fass',
				 'xfc': 1,
				 'xfs': 48,
				 'xs': 48,
				 'yfc': 1,
				 'yfs': 56,
				 'ys': 56},
		143: {   'filename': 'flammenwerfer.bmp',
				 'name': 'Flamethrowher',
				 'type': 'flamethrowher',
				 'xfc': 2,
				 'xfs': 60,
				 'xs': 120,
				 'yfc': 2,
				 'yfs': 60,
				 'ys': 120},
		144: {   'filename': 'gfx/fademusic.bmp',
				 'name': 'FadeMusic',
				 'type': 'fademusic',
				 'xfc': 1,
				 'xfs': 40,
				 'xs': 40,
				 'yfc': 1,
				 'yfs': 40,
				 'ys': 40},
		145: {   'filename': 'gfx/endlevel.bmp',
				 'name': 'End Level',
				 'type': 'end_level',
				 'xfc': 1,
				 'xfs': 120,
				 'xs': 120,
				 'yfc': 1,
				 'yfs': 120,
				 'ys': 120},
		146: {   'filename': 'plattform.bmp',
				 'name': 'Plattform',
				 'type': 'plattform',
				 'xfc': 1,
				 'xfs': 128,
				 'xs': 128,
				 'yfc': 2,
				 'yfs': 32,
				 'ys': 64},
		147: {   'filename': 'presse.bmp',
				 'name': 'Stahlpresse',
				 'type': 'stahlpresse',
				 'xfc': 1,
				 'xfs': 100,
				 'xs': 100,
				 'yfc': 1,
				 'yfs': 256,
				 'ys': 256},
		148: {   'filename': 'trenzshrine.bmp',
				 'name': 'Trenz Shrine',
				 'type': 'trenz_shrine',
				 'xfc': 1,
				 'xfs': 120,
				 'xs': 120,
				 'yfc': 1,
				 'yfs': 180,
				 'ys': 180},
		149: {   'filename': 'bruecke.bmp',
				 'name': 'Bruecke',
				 'type': 'bruecke',
				 'xfc': 1,
				 'xfs': 10,
				 'xs': 10,
				 'yfc': 1,
				 'yfs': 10,
				 'ys': 10},
		150: {   'filename': 'floating.bmp',
				 'name': 'Floating Plattform',
				 'type': 'floating_plattform',
				 'xfc': 1,
				 'xfs': 39,
				 'xs': 39,
				 'yfc': 1,
				 'yfs': 14,
				 'ys': 14},
		151: {   'filename': 'floating2.bmp',
				 'name': 'Floating Plattform2',
				 'type': 'floating_plattform2',
				 'xfc': 1,
				 'xfs': 110,
				 'xs': 110,
				 'yfc': 1,
				 'yfs': 18,
				 'ys': 18},
		152: {   'filename': 'floating3.bmp',
				 'name': 'Floating Plattfor3',
				 'type': 'floating_plattfor3',
				 'xfc': 1,
				 'xfs': 100,
				 'xs': 100,
				 'yfc': 2,
				 'yfs': 27,
				 'ys': 54},
		153: {   'filename': 'gfx/surfbrett.bmp',
				 'name': 'Surfbrett',
				 'type': 'surfbrett',
				 'xfc': 1,
				 'xfs': 52,
				 'xs': 52,
				 'yfc': 1,
				 'yfs': 35,
				 'ys': 35},
		154: {   'filename': 'shootplattformbutton.bmp',
				 'name': 'Nicht setzen!',
				 'type': 'nicht_setzen',
				 'xfc': 2,
				 'xfs': 16,
				 'xs': 32,
				 'yfc': 1,
				 'yfs': 9,
				 'ys': 9},
		155: {   'filename': 'shootplattform.bmp',
				 'name': 'Shoot-Plattform',
				 'type': 'shoot_plattform',
				 'xfc': 1,
				 'xfs': 100,
				 'xs': 100,
				 'yfc': 1,
				 'yfs': 54,
				 'ys': 54},
		156: {   'filename': 'glubschi.bmp',
				 'name': 'Glubschi',
				 'type': 'glubschi',
				 'xfc': 10,
				 'xfs': 51,
				 'xs': 510,
				 'yfc': 3,
				 'yfs': 120,
				 'ys': 360},
		157: {   'filename': 'glubschi2.bmp',
				 'name': 'Glubschi2',
				 'type': 'glubschi2',
				 'xfc': 10,
				 'xfs': 51,
				 'xs': 510,
				 'yfc': 3,
				 'yfs': 120,
				 'ys': 360},
		158: {   'filename': 'column.bmp',
				 'name': 'Column',
				 'type': 'column',
				 'xfc': 1,
				 'xfs': 40,
				 'xs': 40,
				 'yfc': 1,
				 'yfs': 100,
				 'ys': 100},
		159: {   'filename': 'lift.bmp',
				 'name': 'Exploding Lift',
				 'type': 'exploding_lift',
				 'xfc': 1,
				 'xfs': 80,
				 'xs': 80,
				 'yfc': 10,
				 'yfs': 23,
				 'ys': 230},
		160: {   'filename': 'column.bmp',
				 'name': 'Column2',
				 'type': 'column2',
				 'xfc': 1,
				 'xfs': 40,
				 'xs': 40,
				 'yfc': 1,
				 'yfs': 100,
				 'ys': 100},
		161: {   'filename': 'Schleuse.bmp',
				 'name': 'Schleuse Horizontal',
				 'type': 'schleuse_horizontal',
				 'xfc': 1,
				 'xfs': 200,
				 'xs': 200,
				 'yfc': 1,
				 'yfs': 40,
				 'ys': 40},
		162: {   'filename': 'Schleuse2.bmp',
				 'name': 'Schleuse Vertikal',
				 'type': 'schleuse_vertikal',
				 'xfc': 1,
				 'xfs': 40,
				 'xs': 40,
				 'yfc': 1,
				 'yfs': 200,
				 'ys': 200},
		163: {   'filename': 'switch.bmp',
				 'name': 'Schalter',
				 'type': 'schalter',
				 'xfc': 2,
				 'xfs': 24,
				 'xs': 48,
				 'yfc': 1,
				 'yfs': 32,
				 'ys': 32},
		164: {   'filename': 'warning.png',
				 'name': 'Warnungsschild ',
				 'type': 'warnungsschild_',
				 'xfc': 1,
				 'xfs': 180,
				 'xs': 180,
				 'yfc': 1,
				 'yfs': 40,
				 'ys': 40},
		165: {   'filename': 'gfx/soundtrigger.bmp',
				 'name': 'Soundemitter',
				 'type': 'soundemitter',
				 'xfc': 1,
				 'xfs': 40,
				 'xs': 40,
				 'yfc': 1,
				 'yfs': 40,
				 'ys': 40},
		166: {   'filename': 'luefter_gross.png',
				 'name': 'Grosser Luefter',
				 'type': 'grosser_luefter',
				 'xfc': 1,
				 'xfs': 224,
				 'xs': 224,
				 'yfc': 1,
				 'yfs': 223,
				 'ys': 223},
		167: {   'filename': 'luefter1.png',
				 'name': 'Kleiner Luefter',
				 'type': 'kleiner_luefter',
				 'xfc': 4,
				 'xfs': 113,
				 'xs': 453,
				 'yfc': 3,
				 'yfs': 114,
				 'ys': 343},
		168: {   'filename': 'luefter2.png',
				 'name': 'Kleiner kaputter Luefter',
				 'type': 'kleiner_kaputter_luefter',
				 'xfc': 4,
				 'xfs': 113,
				 'xs': 453,
				 'yfc': 3,
				 'yfs': 114,
				 'ys': 343},
		169: {   'filename': 'gfx/tutorialtext.bmp',
				 'name': 'Tutorial Text',
				 'type': 'tutorial_text',
				 'xfc': 1,
				 'xfs': 40,
				 'xs': 40,
				 'yfc': 1,
				 'yfs': 40,
				 'ys': 40},
		170: {   'filename': 'lavaflare.bmp',
				 'name': 'LightFlare',
				 'type': 'lightflare',
				 'xfc': 1,
				 'xfs': 120,
				 'xs': 120,
				 'yfc': 1,
				 'yfs': 120,
				 'ys': 120},
		171: {   'filename': 'gfx/secret.bmp',
				 'name': 'Secret',
				 'type': 'secret',
				 'xfc': 1,
				 'xfs': 40,
				 'xs': 40,
				 'yfc': 1,
				 'yfs': 40,
				 'ys': 40},
		172: {   'filename': 'mushroom_head.png',
				 'name': 'Mushroom',
				 'type': 'mushroom',
				 'xfc': 1,
				 'xfs': 135,
				 'xs': 135,
				 'yfc': 1,
				 'yfs': 61,
				 'ys': 61},
		173: {   'filename': 'presswurst.png',
				 'name': 'Presswurst',
				 'type': 'presswurst',
				 'xfc': 1,
				 'xfs': 185,
				 'xs': 185,
				 'yfc': 1,
				 'yfs': 357,
				 'ys': 357},
		174: {   'filename': 'lafass_spawner.png',
				 'name': 'La Fass Spawner',
				 'type': 'la_fass_spawner',
				 'xfc': 1,
				 'xfs': 74,
				 'xs': 74,
				 'yfc': 1,
				 'yfs': 165,
				 'ys': 165},
		175: {   'filename': 'spikelift.bmp',
				 'name': 'Spikelift',
				 'type': 'spikelift',
				 'xfc': 1,
				 'xfs': 460,
				 'xs': 460,
				 'yfc': 1,
				 'yfs': 80,
				 'ys': 80},
		176: {   'filename': 'tube.png',
				 'name': 'Glasroehre',
				 'type': 'glasroehre',
				 'xfc': 4,
				 'xfs': 100,
				 'xs': 400,
				 'yfc': 1,
				 'yfs': 220,
				 'ys': 220},
		200: {   'filename': 'extras.png',
				 'xfc': 13,
				 'xfs': 24,
				 'xs': 312,
				 'yfc': 1,
				 'yfs': 24,
				 'ys': 24}
	    }
